
sudo: required
services:
  - docker

before_install:
  - docker build -t newprojecttest:1 -f ./client/Dockerfile.dev ./client

script:
  - docker run newprojecttest:1 npm test -- --coverage

after_success:
  - docker build -t 7015214645/multi-client ./client
  - docker build -t 7015214645/multi-nginx ./nginx
  - docker build -t 7015214645/multi-server ./server
  - docker build -t 7015214645/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push 7015214645/multi-client
  - docker push 7015214645/multi-nginx
  - docker push 7015214645/multi-server
  - docker push 7015214645/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: MyDockerApp
  env: Mydockerapp-env-22
  bucket_name: elasticbeanstalk-us-east-2-863659641122
  bucket_path: Mydockerapp-env-22
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
   # secure: $AWS_SECRET_KEY
